---
- name: install APT packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
    cache_valid_time: 86400
  with_items: buildbot_slave_apt_packages

- name: Install PIP packages
  pip:
    name: "{{ item }}"
  with_items: buildbot_slave_pip_packages

- name: User
  user:
    name: '{{ buildbot_slave_user }}'
    comment: 'Dedicated user to run the buildbot slave'
    shell: '/bin/bash'

- name: Folder
  file:
    path: "{{ item }}"
    state: directory
    owner: '{{ buildbot_slave_user }}'
    group: '{{ buildbot_slave_user }}'
  with_items:
  - '{{ buildbot_slave_basedir }}'
  - '{{ buildbot_slave_prepare_dir }}'

- name: Generate Slave Password
  set_fact:
    generated_slave_password: '{{ buildbot_slave_password }}'

- name: Create
  command: >
    buildslave create-slave {{ buildbot_slave_basedir }}
    {{ buildbot_slave_master_host }}:{{ buildbot_slave_master_port }}
    {{ buildbot_slave_name }} {{ generated_slave_password }}
  sudo: yes
  sudo_user: '{{ buildbot_slave_user }}'
  args:
    creates: '{{ buildbot_slave_basedir }}/buildbot.tac'
  notify:
  - reconfig buildslave
  - restart buildslave

- name: Admin
  file:
    content: "{{ buildbot_slave_admin }}"
    dest: '{{ buildbot_slave_basedir }}/info/admin'

- name: Description
  file:
    content: "{{ buildbot_slave_description }}"
    dest: '{{ buildbot_slave_basedir }}/info/host'

- name: Export Facts
  set_fact:
    buildbot_master_host: '{{ buildbot_master_host }}'
    buildbot_slave_user: '{{ buildbot_slave_user }}'
    buildbot_slave_basedir: '{{ buildbot_slave_basedir }}'
    buildbot_slave_prepare_dir: '{{ buildbot_slave_prepare_dir }}'
    buildbot_slave_setups: []
  tags:
  - facts
