---
- name: config
  file:
    path: '{{ buildbot_master_projects_dir }}/{{ project_name }}.yml'
    state: absent
  sudo: yes
  sudo_user: '{{ buildbot_master_user }}'
  notify:
  - reconfig buildmaster
